version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser --snapshot --clean

  build-single:
    desc: Build (single)
    cmds:
      - goreleaser build --snapshot --clean --single-target --output dist/ghr-installer

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go run github.com/psampaz/go-mod-outdated@v0.9.0 -update -direct

  test:
    desc: Test
    deps: [ build-single ]
    cmds:
      - dist/ghr-installer install --base-directory tmp caddyserver/caddy@2.7.6
      - dist/ghr-installer install --base-directory tmp ory/hydra@2.1.2
      - dist/ghr-installer install --base-directory tmp prometheus/prometheus@2.48.1
      - dist/ghr-installer install --base-directory tmp jdx/mise@2024.1.16
      - dist/ghr-installer install --base-directory tmp oauth2-proxy/oauth2-proxy@7.5.1
    ignore_error: true
